# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies
install: pip install -U tox-travis

# Command to run tests
script: tox

deploy:

  # Automatically deploy releases to PyPI for each tagged commit
  # Assuming you have installed the travis-ci CLI tool, after you
  # create the Github repo and add it to Travis, run the
  # following command to finish PyPI deployment setup:
  # $ travis encrypt MY_PYPI_PASSWORD
  # and then copy the (really long) encrypted password as shown.
  - provider: pypi
    distributions: sdist bdist_wheel
    user: dai_lab_mit
    password:
      secure: "DZpyAQdn1Kax0lnrXRTF/GsP/+FdtuaPY8dwGyGS0tgD9LukOVScqemxfpi4KdrP+H0W9ELJ33dxrzeNN53LMm+Cf3rQ9kaoGy54JAYfV4j4osF7fghDXCpdOZGylBsy0tRHqsczS7m97zIA349/bNoiSOBTUuVSbJMP+G36qaqvX3Dc2moeN5yCvGWURAcEGMH/nBGirysuqEPK+Au/ohgt5tbWRsAnWzKslsuci7pOh4EqkH57QENPtj2eLIY5dqZPR+g9reUnZsLZWRRBpvEGV863dw4YaJ7RPNjBGyrD1yAJPtfYf+k9AKBfqULOsk0xqMvO43z/3hptMSCB2s8AmsPMIKbPKX4GvFCOF+u9KRbjFnsAz1p+TCzj0Nzxk503KB8xdPrXy0Aw82y0bSuaziGy1ubzzMQZ7qq+5Coa0nlAyOuyd2AJxwy5Sz0Mk+3b40LPWuAmhxuwNRnwvaWKWhtGEomhV7RD4mX/LJzge/UMFlRiL3sjHbdFK4UFdCKoJoXbF1yxe01ZwPhDscuSOzQjDV/2mVlYEVGj3jjLC8TJD6jz2md0sAOlIlK0+EZru0piD8kRGMSELOlDTcjNqkNWu3oSwrfszPaCG0xbUUsuo863mPlxrU/Q5BbO3z67aYC81BKjSPhwLiKV/E6sI1FjDufIE5yrnAQKYpQ="
    on:
      tags: true
      repo: HDI-Project/BTB
      python: 3.6

  # Automatically build and deploy documentation to GitHub Pages after every
  # commit
  # Follow the instructions at https://docs.travis-ci.com/user/deployment/pages/
  # to setup a personal deployment token and then provide it as a secure
  # environment variable at https://travis-ci.org/HDI-Project/btb/settings
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: master
      python: 3.6

