dask_cluster:
  worker_config:
    image: mlbazaar/btb_benchmark:latest
    resources:
      cpu: 7
      memory: 4G
  workers: 52
run:
  args:
    challenge_types: xgboost
    iterations: 100
  function: btb_benchmark.main.run_benchmark
